### PR TITLE
parse command line arguments and open urls

### LINKED ISSUE #99: Commandline argument support?
I might be missing something, but it seems that `next` does not support commandline arguments at the moment.  That is,

```
next <some-url>
```
fires up Next and opens the start page, not `<some-url>`.

I can provide a patch if required.

### PR DESCRIPTION
**Pull request by vindarel**
I suggest this. We can put many urls as arguments and interleave them with `-h` or `-v`.

fixes #99

### CODE REVIEW

**Comment by jmercouris** [comment]
Hey! Thank you for the pull request! I'll get to testing this ASAP!!!

**Comment by jmercouris** [comment]
There's some strange behavior happening here:

screen shot 2018-05-26 at 11 08 16

Not sure why it is, perhaps somehow unix-opts isn't being saved into the image?

**Comment by vindarel** [comment]
unix-opts is a wrapper library, it should work for CCL too. Strange indeed. 

```

**Comment by jmercouris** [comment]
I can't get it to work on CCL, but it doesn't much matter as CCL is intended for OSX where it is meant to really be launched as an APP bundle.

I would just like to confirm that you've tested it with SBCL and it works, if so, I'll go ahead and merge this, thanks!

**Comment by vindarel** [comment]
I can confirm on SBCL :)

selection_237

**Comment by jmercouris** [comment]
Thank you :)!

**Pull request merged**
