### PR TITLE
Added reload page, scroll page up/down, scroll to top and bottom

### PR DESCRIPTION
**Pull request by cjohansson**
Hi I added some basic examples of how to make a key-binding for reload page, scroll page up/down, scroll to top/bottom in the documentation.

### CODE REVIEW

**Comment by jmercouris** [comment]
Hi, sorry for the delay in reviewing this! I thought at first that it was duplicate code, but I see now that you multiply the scroll distance by a factor of 10 to scroll a single page :D my apologies. Do you mind if I do a little formatting after I merge it?

**Comment by jmercouris** [comment]
Also, before I forget,  thank you for the contribution! I appreciate your interest and support!

**Comment by cjohansson** [comment]
Sure, you can do any changes you want, I figured someone else might also look for this. Also examples make it easier to get started with customization 😀

**Comment by lehmacdj** [comment]
Just in case you are interested you could also use the following snippet to scroll a page regardless of the size of the web browser.

```
(defparenstatic scroll-page-down
    (ps:chain window (scroll-by 0 (ps:@ window inner-height))))
(defparenstatic scroll-page-up
  (ps:chain window (scroll-by 0 (- (ps:@ window inner-height)))))
```

**Comment by jmercouris** [comment]
@lehmacdj I've taken your suggestions into account when merging this, thank you :)

definitely very handy to have it be dynamic!

**Comment by cjohansson** [comment]
Great, works even better now. I didn't see that scroll to top/bottom already existed as a default keybinding

**Comment by jmercouris** [comment]
No problem :)

it was added recently in the latest version I think, so I can see why you might have missed it!

**Pull request merged**
