### PR TITLE
add: function to bookmark current-url

### PR DESCRIPTION
**Pull request by watkinsr**
Would be nice to bookmark the current URL I think.

### CODE REVIEW

**Comment by jmercouris** [comment]
Hi, thank you very much for your interest!

Your function is nice and clean, but I believe that it has the same functionality as:

‘’’bookmark-current-page’’’

so perhaps instead clean up bookmark-current-page and implement it in the same way, or make an alias or something, I’m not sure.

**Comment by watkinsr** [comment]
@jmercouris as far as I could tell and manually test. "BOOKMARK-CURRENT-PAGE" will only bookmark the buffer name. It does not get the latest URL so if you happened to navigate away from the initially entered URL, it would bookmark the first entry. Hence, the need for this function.

**Comment by jmercouris** [comment]
Ah, I understand now, my apologies! Thank you for the clarification!!!

**Comment by jmercouris** [comment]
Congratulations! to the first of hopefully many more :)


if you need tasks, I have a huge list :D

**Comment by watkinsr** [comment]
@jmercouris Could you send the list through to ryanwatkins54@gmail.com ? 👍

**Comment by Ambrevar** [comment]
Better: could you publish it in the repo?
An Org file would be great! :)

**Comment by jmercouris** [comment]
I usually have a task list for each version in the developer readme at the bottom, if you open it in org mode you can see it,

the only problem with that is that it tracks predictable and major releases, I tend not to put really ambitious and speculative projects, such as the current branch that I am working on, I can probably link to that branch though,

-John

**Pull request merged**
